### PR TITLE
Remove unnecessary files

### PR DESCRIPTION
**Pull request by yutax77**
Remove unnecessary files generated by Eclipse.
* .classpath
* .project
* .settings/

Since now using git, `.csvignore` also unnecessary.

### CODE REVIEW

**Comment by WolfgangFahl** [comment]
Unneccessary? Eclipse is the development environment for one of the committers, namely me ...

**Comment by yutax77** [comment]
httpunit is maven project.
So, if m2e plugin is installed in eclipse, we can import httpunit without such files(.classpath, .settings ...)
`File -> Import -> Existing Maven Projects`

Furthermore, such files do not often to be included in the VCS(svn, git).
http://stackoverflow.com/questions/8169941/should-eclipse-specific-files-in-an-vcs-be-ignored-if-using-maven

I ask you to give this matter your consideration.

**Comment by WolfgangFahl** [comment]
Thank you for your comment. The files do no harm if they are there. If they are missing this is extra work for the committers. That's why the files stay in git for the time being.

**Comment by yutax77** [comment]
Thank you for your correspondence.
I understand it.

**Pull request closed without merging**
